Taipei_URL = https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json
New_Taipei_URL = https://data.ntpc.gov.tw/api/datasets/010e5b15-3823-4b20-b401-b1cf000550c5/json?size=100
Kaohsiung_URL = https://api.kcg.gov.tw:443/api/service/Get/b4dd9c40-9027-4125-8666-06bef1756092
Taoyuan_URL = http://data.tycg.gov.tw/api/v1/rest/datastore/a1b4714b-3b75-4ff8-a8f2-cc377e4eaa0f?format=json